use_frameworks!

platform :ios, '10.0'

target 'JuswinProtocol_Example' do
  pod 'JuswinProtocol', :path => '../'

  target 'JuswinProtocol_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
